### ISSUE TITLE
bug: AttributeError: 'dict' object has no attribute 'resolve_closest'

### ISSUE THREAD

**Issue by kumaranvpl** [mkdocstrings/autorefs#57] opened 2024-09-04 14:11 UTC
### Description of the bug
From version `1.2.0`, running `mkdocs build` command results in the error `AttributeError: 'dict' object has no attribute 'resolve_closest'`. This issue is not happening in version `1.1.0`.

I did some digging around, the error obviously happening at https://github.com/mkdocstrings/autorefs/blob/main/src/mkdocs_autorefs/plugin.py#L178 and the `self.config` returns an empty dictionary. Even at `on_config` https://github.com/mkdocstrings/autorefs/blob/main/src/mkdocs_autorefs/plugin.py#L211, the `self.config` value is an empty dictionary. But printing the `self.config` in `mkdocstrings` project at https://github.com/mkdocstrings/mkdocstrings/blob/main/src/mkdocstrings/plugin.py#L137 returns some value.

This could be because of incorrect initialization/usage of config variable. Hopefully above info helps with debugging.

### Full traceback
<details><summary>Full traceback</summary>

```python
File "/home/userdev/project/venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/userdev/project/venv/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userdev/project/venv/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/userdev/project/venv/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userdev/project/venv/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userdev/project/venv/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userdev/project/venv/lib/python3.12/site-packages/mkdocs/__main__.py", line 288, in build_command
    build.build(cfg, dirty=not clean)
  File "/home/userdev/project/venv/lib/python3.12/site-packages/mkdocs/commands/build.py", line 337, in build
    _build_page(
  File "/home/userdev/project/venv/lib/python3.12/site-packages/mkdocs/commands/build.py", line 226, in _build_page
    output = config.plugins.on_post_page(output, page=page, config=config)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userdev/project/venv/lib/python3.12/site-packages/mkdocs/plugins.py", line 646, in on_post_page
    return self.run_event('post_page', output, page=page, config=config)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userdev/project/venv/lib/python3.12/site-packages/mkdocs/plugins.py", line 566, in run_event
    result = method(item, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userdev/project/venv/lib/python3.12/site-packages/mkdocs_autorefs/plugin.py", line 315, in on_post_page
    fixed_output, unmapped = fix_refs(output, url_mapper, _legacy_refs=self.legacy_refs)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userdev/project/venv/lib/python3.12/site-packages/mkdocs_autorefs/references.py", line 412, in fix_refs
    html = AUTOREF_RE.sub(fix_ref(url_mapper, unmapped), html)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userdev/project/venv/lib/python3.12/site-packages/mkdocs_autorefs/references.py", line 369, in inner
    url = url_mapper(unescape(identifier))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userdev/project/venv/lib/python3.12/site-packages/mkdocs_autorefs/plugin.py", line 211, in get_item_url
    url = self._get_item_url(identifier, fallback, from_url)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/userdev/project/venv/lib/python3.12/site-packages/mkdocs_autorefs/plugin.py", line 185, in _get_item_url
    if self.config.resolve_closest and from_url is not None:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'resolve_closest'
```

</details>

### Environment information
- __System__: Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
- __Python__: cpython 3.12.5
- __Environment variables__:
- __Installed packages__:
  - `mkdocs-autorefs` v1.2.0

**Comment by pawamoy** [comment] 2024-09-05 14:48
Thanks for the report @kumaranvpl. Could you tell me which version of MkDocs you have installed?

**Comment by kumaranvpl** [comment] 2024-09-05 17:09
Hello @pawamoy,

I am using following version of libraries:

```txt
mkdocs                                    1.6.1
mkdocs-autorefs                           1.2.0
mkdocstrings                              0.26.0
mkdocstrings-python                       1.10.9
```

**Comment by pawamoy** [comment] 2024-09-05 22:30
Thanks @beijbom. Still cannot reproduce though, so yes, a full repo would be great :slightly_smiling_face:

**Comment by kumaranvpl** [comment] 2024-09-06 05:02
> Thanks for the report @kumaranvpl. Could you tell me which version of MkDocs you have installed?

Hello @pawamoy,

Checkout my repo - https://github.com/kumaranvpl/faststream/tree/main. Please clone it, create a venv(any 3.9+), install dependencies by running `pip install -e ".[dev]"` and run the script `./scripts/build-docs.sh`. 

This will throw the error `AttributeError: 'dict' object has no attribute 'resolve_closest'`. I hope this helps with your debugging.

**Comment by bls-amid** [comment] 2024-09-06 05:53
We also encountered this error when upgrading **mkdocstrings** to v.0.26.0 which included an upgrade of **autorefs** to 1.2.0

We added the following to the `mkdocs.yml` as a workaround, but would be nice if it was not necessary

![image](https://github.com/user-attachments/assets/45ba5c38-ec9e-4d81-97e3-7af31db5bfcc)

**Comment by pawamoy** [comment] 2024-09-06 09:51
@kumaranvpl thanks, I'm able to reproduce the error within your repository. However that's far from a minimal reproduction example and that makes it hard to debug. Basically, in your project, `self.config` is indeed an empty dict, while in my own (smaller) projects, `self.config` is an instance of `mkdocs_autorefs.plugin.AutorefsConfig`, which allows attribute access, and has `resolve_closest` set to `False` by default. What I don't understand is why the types are different from one project to another. This is why an MRE would be greatly appreciated.

**Comment by pawamoy** [comment] 2024-09-06 10:04
OK I found the difference. It's when `autorefs` is listed or not under `plugins`. Working on a fix.

**Comment by pawamoy** [comment] 2024-09-06 10:26
Fixed by mkdocstrings 0.26.1, which now instantiates the `config` attribute of the autorefs plugin instance it creates itself.

**Closed by pawamoy** 2024-09-06 10:26 UTC
Labels: unconfirmed

**Comment by bls-amid** [comment] 2024-09-06 10:51
Can confirm that 0.26.1 allows us to remove the aforementioned workaround - thanks for the quick fix!

**Comment by kumaranvpl** [comment] 2024-09-06 12:03
@pawamoy Thanks for the quick fix. I can also confirm that with version `0.26.1` my project works. Sorry, I didn't had time to create a MRE.

**Comment by pawamoy** [comment] 2024-09-06 12:05
No worries, you were all helpful 😊
